import type { MetricColumn } from '@/types';

export const METRIC_COLUMNS: MetricColumn[] = [
  // Basic Metrics
  {
    id: 'impressions',
    label: 'Impressions',
    shortLabel: 'Impr',
    format: 'number',
    category: 'basic',
    defaultVisible: true,
    width: 110,
    align: 'right',
  },
  {
    id: 'clicks',
    label: 'Clicks',
    shortLabel: 'Clicks',
    format: 'number',
    category: 'basic',
    defaultVisible: true,
    width: 90,
    align: 'right',
  },
  {
    id: 'ctr',
    label: 'Click-Through Rate',
    shortLabel: 'CTR',
    format: 'percentage',
    category: 'basic',
    defaultVisible: true,
    width: 90,
    align: 'right',
  },

  // Cost Metrics
  {
    id: 'cost',
    label: 'Cost',
    shortLabel: 'Cost',
    format: 'currency',
    category: 'costs_revenue',
    defaultVisible: true,
    width: 110,
    align: 'right',
  },
  {
    id: 'cpc',
    label: 'Cost Per Click',
    shortLabel: 'CPC',
    format: 'currency',
    category: 'costs_revenue',
    defaultVisible: true,
    width: 90,
    align: 'right',
  },
  {
    id: 'cpm',
    label: 'Cost Per Mille',
    shortLabel: 'CPM',
    format: 'currency',
    category: 'costs_revenue',
    defaultVisible: true,
    width: 90,
    align: 'right',
  },

  // Conversion Metrics
  {
    id: 'conversions',
    label: 'Conversions',
    shortLabel: 'Conv',
    format: 'number',
    category: 'conversions',
    defaultVisible: true,
    width: 90,
    align: 'right',
  },

  // CRM Metrics (order matches dashboard: Cust, Subs, Trials, Trial Appv, Trial Appr.%, OTS, OTS Appr.%, Upsells, Ups. Appv %, Real CPA)
  {
    id: 'customers',
    label: 'Customers',
    shortLabel: 'Cust',
    description: 'Registration date = subscription date. Date range on subscription creation. Excludes parent-sub-id tagged.',
    format: 'number',
    category: 'conversions',
    defaultVisible: true,
    width: 90,
    align: 'right',
  },
  {
    id: 'subscriptions',
    label: 'Subscriptions',
    shortLabel: 'Subs',
    description: 'Unique subscription count. Date range on subscription creation. Excludes parent-sub-id tagged.',
    format: 'number',
    category: 'conversions',
    defaultVisible: true,
    width: 90,
    align: 'right',
  },
  {
    id: 'trialsApproved',
    label: 'Trials',
    shortLabel: 'Trials',
    description: 'Invoice type 1, not deleted, marked as approved. Date range on invoice order date. Upsells counted separately.',
    format: 'number',
    category: 'conversions',
    defaultVisible: true,
    width: 90,
    align: 'right',
  },
  {
    id: 'approvalRate',
    label: 'Trial Appr. %',
    shortLabel: 'Trial Appr. %',
    description: 'Approved trials / subscriptions.',
    format: 'percentage',
    category: 'conversions',
    defaultVisible: true,
    width: 100,
    align: 'right',
  },
  {
    id: 'onHold',
    label: 'On Hold',
    shortLabel: 'On Hold',
    description: 'Invoice type 1, not deleted, on-hold date set. Date range on invoice order date.',
    format: 'number',
    category: 'conversions',
    defaultVisible: true,
    width: 90,
    align: 'right',
  },
  {
    id: 'ots',
    label: 'OTS',
    shortLabel: 'OTS',
    description: 'Invoice type 3, not deleted. Date range on invoice order date.',
    format: 'number',
    category: 'conversions',
    defaultVisible: true,
    width: 90,
    align: 'right',
  },
  {
    id: 'otsApprovalRate',
    label: 'OTS Appr. %',
    shortLabel: 'OTS Appr. %',
    description: 'Approved OTS / total OTS.',
    format: 'percentage',
    category: 'conversions',
    defaultVisible: true,
    width: 120,
    align: 'right',
  },
  {
    id: 'upsells',
    label: 'Upsells',
    shortLabel: 'Upsells',
    description: 'Invoices matched via parent-sub-id tag. Includes trial and OTS types. Date range on parent subscription creation.',
    format: 'number',
    category: 'conversions',
    defaultVisible: true,
    width: 90,
    align: 'right',
  },
  {
    id: 'upsellApprovalRate',
    label: 'Upsell Appv %',
    shortLabel: 'Ups. Appv %',
    description: 'Approved upsells / total upsells.',
    format: 'percentage',
    category: 'conversions',
    defaultVisible: true,
    width: 120,
    align: 'right',
  },
  {
    id: 'realCpa',
    label: 'Real CPA',
    shortLabel: 'Real CPA',
    description: 'Ad spend / approved trials.',
    format: 'currency',
    category: 'conversions',
    defaultVisible: true,
    width: 110,
    align: 'right',
  },
];

export const MARKETING_METRIC_IDS = ['impressions', 'clicks', 'ctr', 'cost', 'cpc', 'cpm', 'conversions'] as const;
export const CRM_METRIC_IDS = ['customers', 'subscriptions', 'trialsApproved', 'approvalRate', 'onHold', 'ots', 'otsApprovalRate', 'upsells', 'upsellApprovalRate'] as const;

export const DEFAULT_VISIBLE_COLUMNS = METRIC_COLUMNS
  .filter((col) => col.defaultVisible)
  .map((col) => col.id);
