import type { MetricColumn } from '@/types';

export const METRIC_COLUMNS: MetricColumn[] = [
  // Basic Metrics
  {
    id: 'impressions',
    label: 'Impressions',
    shortLabel: 'Impr',
    format: 'number',
    category: 'basic',
    defaultVisible: true,
    width: 110,
    align: 'right',
  },
  {
    id: 'clicks',
    label: 'Clicks',
    shortLabel: 'Clicks',
    format: 'number',
    category: 'basic',
    defaultVisible: true,
    width: 90,
    align: 'right',
  },
  {
    id: 'ctr',
    label: 'Click-Through Rate',
    shortLabel: 'CTR',
    format: 'percentage',
    category: 'basic',
    defaultVisible: true,
    width: 90,
    align: 'right',
  },

  // Cost Metrics
  {
    id: 'cost',
    label: 'Cost',
    shortLabel: 'Cost',
    format: 'currency',
    category: 'costs_revenue',
    defaultVisible: true,
    width: 110,
    align: 'right',
  },
  {
    id: 'cpc',
    label: 'Cost Per Click',
    shortLabel: 'CPC',
    format: 'currency',
    category: 'costs_revenue',
    defaultVisible: true,
    width: 90,
    align: 'right',
  },
  {
    id: 'cpm',
    label: 'Cost Per Mille',
    shortLabel: 'CPM',
    format: 'currency',
    category: 'costs_revenue',
    defaultVisible: true,
    width: 90,
    align: 'right',
  },

  // Conversion Metrics
  {
    id: 'conversions',
    label: 'Conversions',
    shortLabel: 'Conv',
    format: 'number',
    category: 'conversions',
    defaultVisible: true,
    width: 90,
    align: 'right',
  },

  // CRM Metrics (order matches dashboard: Cust, Subs, Trials, Approved, Appr.%, OTS, OTS Appr.%, Upsells, Ups. Appv %, Real CPA)
  {
    id: 'customers',
    label: 'Customers',
    shortLabel: 'Cust',
    description: 'New customers (registration date = subscription date)',
    format: 'number',
    category: 'conversions',
    defaultVisible: true,
    width: 90,
    align: 'right',
  },
  {
    id: 'subscriptions',
    label: 'Subscriptions',
    shortLabel: 'Subs',
    description: 'Total subscriptions matched by tracking IDs from the CRM',
    format: 'number',
    category: 'conversions',
    defaultVisible: true,
    width: 90,
    align: 'right',
  },
  {
    id: 'trials',
    label: 'Trials',
    shortLabel: 'Trials',
    description: 'Trial invoices (type = 1) matched by tracking IDs',
    format: 'number',
    category: 'conversions',
    defaultVisible: true,
    width: 90,
    align: 'right',
  },
  {
    id: 'trialsApproved',
    label: 'Approved',
    shortLabel: 'Approved',
    description: 'Approved trial invoices (is_marked = 1)',
    format: 'number',
    category: 'conversions',
    defaultVisible: true,
    width: 100,
    align: 'right',
  },
  {
    id: 'approvalRate',
    label: 'Approval %',
    shortLabel: 'Appr. %',
    description: 'Percentage of trials + OTS approved ((trialsApproved + otsApproved) / (trials + ots))',
    format: 'percentage',
    category: 'conversions',
    defaultVisible: true,
    width: 100,
    align: 'right',
  },
  {
    id: 'ots',
    label: 'OTS',
    shortLabel: 'OTS',
    description: 'One-time sale invoices (invoice type 3)',
    format: 'number',
    category: 'conversions',
    defaultVisible: true,
    width: 90,
    align: 'right',
  },
  {
    id: 'otsApprovalRate',
    label: 'OTS Appr. %',
    shortLabel: 'OTS Appr. %',
    description: 'Percentage of OTS approved (otsApproved / ots)',
    format: 'percentage',
    category: 'conversions',
    defaultVisible: true,
    width: 120,
    align: 'right',
  },
  {
    id: 'upsells',
    label: 'Upsells',
    shortLabel: 'Upsells',
    description: 'Upsell invoices matched by tracking IDs',
    format: 'number',
    category: 'conversions',
    defaultVisible: true,
    width: 90,
    align: 'right',
  },
  {
    id: 'upsellApprovalRate',
    label: 'Upsell Appv %',
    shortLabel: 'Ups. Appv %',
    description: 'Percentage of upsells approved (upsellsApproved / upsells)',
    format: 'percentage',
    category: 'conversions',
    defaultVisible: true,
    width: 120,
    align: 'right',
  },
  {
    id: 'realCpa',
    label: 'Real CPA',
    shortLabel: 'Real CPA',
    description: 'Cost / approved subs',
    format: 'currency',
    category: 'conversions',
    defaultVisible: true,
    width: 110,
    align: 'right',
  },
];

export const MARKETING_METRIC_IDS = ['impressions', 'clicks', 'ctr', 'cost', 'cpc', 'cpm', 'conversions'] as const;
export const CRM_METRIC_IDS = ['customers', 'subscriptions', 'trials', 'trialsApproved', 'approvalRate', 'ots', 'otsApprovalRate', 'upsells', 'upsellApprovalRate'] as const;

export const DEFAULT_VISIBLE_COLUMNS = METRIC_COLUMNS
  .filter((col) => col.defaultVisible)
  .map((col) => col.id);
