import type { MetricColumn } from '@/types';

export const ON_PAGE_METRIC_COLUMNS: MetricColumn[] = [
  // Engagement Metrics
  {
    id: 'pageViews',
    label: 'Page Views',
    shortLabel: 'Views',
    description: 'Total number of page views',
    format: 'number',
    category: 'basic',
    defaultVisible: true,
    width: 100,
    align: 'right',
  },
  {
    id: 'uniqueVisitors',
    label: 'Unique Visitors',
    shortLabel: 'Visitors',
    description: 'Number of unique visitors',
    format: 'number',
    category: 'basic',
    defaultVisible: true,
    width: 100,
    align: 'right',
  },
  {
    id: 'bounceRate',
    label: 'Bounce Rate',
    shortLabel: 'Bounce',
    description: 'Visitors who stayed less than 5 seconds',
    format: 'percentage',
    category: 'basic',
    defaultVisible: true,
    width: 90,
    align: 'right',
  },
  {
    id: 'avgActiveTime',
    label: 'Avg Active Time',
    shortLabel: 'Avg Time',
    description: 'Average time spent on page',
    format: 'time',
    category: 'basic',
    defaultVisible: true,
    width: 120,
    align: 'right',
  },

  // Interaction Metrics
  {
    id: 'scrollPastHero',
    label: 'Scroll Past Hero',
    shortLabel: 'Hero Scroll',
    description: 'Scrolled past hero section',
    format: 'number',
    category: 'conversions',
    defaultVisible: true,
    width: 110,
    align: 'right',
  },
  {
    id: 'scrollRate',
    label: 'Scroll Rate',
    shortLabel: 'Hero Scroll %',
    description: 'Percentage who scrolled past hero',
    format: 'percentage',
    category: 'conversions',
    defaultVisible: true,
    width: 110,
    align: 'right',
  },
  {
    id: 'formViews',
    label: 'Form Views',
    shortLabel: 'Form Views',
    description: 'Number of form views',
    format: 'number',
    category: 'conversions',
    defaultVisible: true,
    width: 110,
    align: 'right',
  },
  {
    id: 'formViewRate',
    label: 'Form View Rate',
    shortLabel: 'Form View %',
    description: 'Percentage who viewed the form',
    format: 'percentage',
    category: 'conversions',
    defaultVisible: true,
    width: 110,
    align: 'right',
  },
  {
    id: 'formStarters',
    label: 'Form Starters',
    shortLabel: 'Form Start',
    description: 'Unique visitors who started the form',
    format: 'number',
    category: 'conversions',
    defaultVisible: true,
    width: 110,
    align: 'right',
  },
  {
    id: 'formStartRate',
    label: 'Form Start Rate',
    shortLabel: 'Form Start %',
    description: 'Conversion rate from view to start',
    format: 'percentage',
    category: 'conversions',
    defaultVisible: true,
    width: 110,
    align: 'right',
  },

  {
    id: 'crmConvRate',
    label: 'Conversion Rate',
    shortLabel: 'Conv %',
    description: 'CRM trials / unique visitors',
    format: 'percentage',
    category: 'crm',
    defaultVisible: true,
    width: 90,
    align: 'right',
  },

  // CRM Metrics
  {
    id: 'crmTrials',
    label: 'CRM Trials',
    shortLabel: 'Trials',
    description: 'CRM subscriptions matched by tracking IDs',
    format: 'number',
    category: 'crm',
    defaultVisible: true,
    width: 90,
    align: 'right',
  },
  {
    id: 'crmApproved',
    label: 'Approved Sales',
    shortLabel: 'Approved',
    description: 'Approved CRM trials (is_marked = 1)',
    format: 'number',
    category: 'crm',
    defaultVisible: true,
    width: 90,
    align: 'right',
  },
  {
    id: 'crmApprovalRate',
    label: 'Approval Rate',
    shortLabel: 'Appr. %',
    description: 'Approved sales / total trials',
    format: 'percentage',
    category: 'crm',
    defaultVisible: true,
    width: 90,
    align: 'right',
  },
];

export const ON_PAGE_DEFAULT_VISIBLE_COLUMNS = ON_PAGE_METRIC_COLUMNS
  .filter((col) => col.defaultVisible)
  .map((col) => col.id);
